# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/cheetah/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),cheetah)

$(call add-radio-file-sha1-checked,radio/abl.img,bafa1f3150333948e9c0c318f883ce905ae3bea9)
$(call add-radio-file-sha1-checked,radio/bl1.img,3029297e3c128a6d91b00156fb9e2937428253f0)
$(call add-radio-file-sha1-checked,radio/bl2.img,d7dd89f26c63bfc8c12d0ab3a8a5be339ed6cd50)
$(call add-radio-file-sha1-checked,radio/bl31.img,a118fb329d8b0575de5e90bbb44f950de59f87ab)
$(call add-radio-file-sha1-checked,radio/gsa.img,81cbb7a5d7268874e4fc404e54d60ef41ee5bbdc)
$(call add-radio-file-sha1-checked,radio/ldfw.img,5d77f38b79a98121900d3759c8634f24aa3407e3)
$(call add-radio-file-sha1-checked,radio/modem.img,0331530cdf89a9d98f4ceecc315233ec69ca3fd9)
$(call add-radio-file-sha1-checked,radio/pbl.img,e0529f603815c8b5b61928956d501c93ff515612)
$(call add-radio-file-sha1-checked,radio/tzsw.img,ee60e9b1c9d670ee6024000619911af2c9620812)

endif
